### PR TITLE
Add support for Pyserini 0.16.0

### PR DESCRIPTION
**Pull request by manveertamber**
Unfortunately, with this change, Pyserini 0.16.0 or above must be used

### CODE REVIEW

**Review by rodrigonogueira4 — APPROVED** [review]
Thanks for fixing this!

**Review by ronakice — APPROVED** [review]
LGTM!

**Comment by manveertamber** [comment]
Hopefully changing spacy==3.0.6 to spacy>=3.2.1 in the requirements.txt doesn't break anything? @rodrigonogueira4  @ronakice Pyserini requires spacy>=3.2.1

**Comment by rodrigonogueira4** [comment]
It will probably give different results. @lintool @MXueguang do you remember why we changed to 3.2.1? I can't remember...

**Comment by lintool** [comment]
Luckily I wrote up everything: https://github.com/castorini/anserini/blob/master/docs/experiments-msmarco-doc-doc2query-details.md

**Pull request merged**
