### PR TITLE
PyGaggle MS MARCO Passage Retrieval Replication

### PR DESCRIPTION
**Pull request by larryli1999**
Platform: Google Colab
GPU: Tesla T4

### Re-Ranking with monoBERT
Capture1

### Re-Ranking with monoT5
Capture2

### CODE REVIEW

**Comment by larryli1999** [comment]
I have the same replication results as https://github.com/castorini/pygaggle/pull/184, which is different from the results shown in the documentation.

**Comment by ronakice** [comment]
@larryli1999 please retry replicating on new master?

**Comment by larryli1999** [comment]
@ronakice I re-run the inference with the updated master and I am able to reproduce the documented results.

### Re-ranking with monoBERT
Capture1


### Re-ranking with monoT5
Capture2

**Comment by ronakice** [comment]
@larryli1999 resolve and I can push, make sure you point to the right commit you reran experiments on!

**Comment by larryli1999** [comment]
@ronakice Done.

**Comment by ronakice** [comment]
Hey @larryli1999, I think the commit is still wrong. Also, there is a merge conflict, please pull upstream fix it and I will merge it.

**Comment by larryli1999** [comment]
Sorry about the conflict, can you check if the commit is right now @ronakice ?

**Comment by ronakice** [comment]
LGTM

**Pull request merged**
