### PR TITLE
CovidQA + MSMARCO doc Replication log

### PR DESCRIPTION
**Pull request by yuxuan-ji**
CovidQA: All identical except for BM25
MS-MARCO doc: Identical
See comments for detailed replication results

### CODE REVIEW

**Comment by yuxuan-ji** [comment]
Keeping this as draft for now as I wasn't able to replicate BM25 results

**Comment by lintool** [comment]
@daemon can you comment?

**Comment by yuxuan-ji** [comment]
### Colab Environment

OS: `Ubuntu 18.04.3 LTS`
Java: `openjdk 11.0.8 2020-07-14`
Python: `Python 3.6.9`
Tested with `Tesla T4`

### Replication results
MS-MARCO doc
1st half: Identical
```
2020-09-09 14:27:13 [INFO] evaluate_document_ranker: Reranking:
100% 25/25 [7:50:24<00:00, 1129.00s/it]
2020-09-09 22:17:38 [INFO] evaluate_document_ranker: precision@1 0.16
2020-09-09 22:17:38 [INFO] evaluate_document_ranker: recall@3    0.44
2020-09-09 22:17:38 [INFO] evaluate_document_ranker: recall@50   0.84
2020-09-09 22:17:38 [INFO] evaluate_document_ranker: recall@1000 0.88
2020-09-09 22:17:38 [INFO] evaluate_document_ranker: mrr         0.33663
2020-09-09 22:17:38 [INFO] evaluate_document_ranker: mrr@10      0.33171
```

**Review by ronakice — APPROVED** [review]
LGTM! Thanks @yuxuan-ji

**Pull request merged**
