### PR TITLE
Simplify boilerplate for monoT5 and monoBERT

### LINKED ISSUE #80: Simplify monoT5 and monoBERT boilerplate
There's a lot of boilerplate here: https://github.com/castorini/pygaggle#a-simple-reranking-example

Can we fold all of that into the constructor of the class? E.g., so we're left with:

```python
reranker =  monoT5()
```

or

```python
reranker =  monoBERT()
```

Make `model_name`, `tokenizer_name`, etc.  configurable with sensical defaults.

So simple reranking gets boiled down to

```python
from pyserini.search import SimpleSearcher
from pygaggle.rerank.base import hits_to_texts

query = Query('who proposed the geocentric theory')
searcher = SimpleSearcher('/path/to/msmarco/index/')
reranker = monoBERT()

hits = searcher.search(query.text)
reranked = reranker.rerank(query, hits_to_texts(hits))
reranked.sort(key=lambda x: x.score, reverse=True)
```

@rodrigonogueira4 @rodrigonogueira4 thoughts?

### PR DESCRIPTION
**Pull request by yuxuan-ji**
closes #80 

usage is like so:
```python
from pygaggle.rerank.pretrained import monoBERT, monoT5
reranker = monoBERT()
or
reranker = monoBERT('model-name', 'tokenizer-name')
or
reranker = monoBERT(model, tokenizer)
```

tested outputs are the same as https://github.com/castorini/pygaggle#a-simple-reranking-example

I was a bit confused on the goal of these two functions, see my comment here: https://github.com/castorini/pygaggle/issues/80#issuecomment-690599468

### CODE REVIEW

**Review by rodrigonogueira4 — APPROVED** [review]
Great, thanks for implementing this!

**Comment by rodrigonogueira4** [comment]
Can you also change the README accordingly?

**Comment by lintool** [comment]
hey @rodrigonogueira4 - do you prefer this impl or the alternative of folding the boilerplate code into constructors for existing models? e.g., https://github.com/castorini/pygaggle/blob/master/pygaggle/rerank/transformer.py#L25

**Comment by rodrigonogueira4** [comment]
> hey @rodrigonogueira4 - do you prefer this impl or the alternative of folding the boilerplate code into constructors for existing models? e.g., https://github.com/castorini/pygaggle/blob/master/pygaggle/rerank/transformer.py#L25

Yes, it is actually better to rename `T5Reranker` to `monoT5` and add the option to initialize it without arguments.

**Comment by yuxuan-ji** [comment]
@rodrigonogueira4 @lintool which do you prefer?

folding into constructors:
```python
class T5Reranker(Reranker):
    def __init__(self,
                 model: T5ForConditionalGeneration = None,
                 tokenizer: QueryDocumentBatchTokenizer = None):
        if not model:
            device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
            model = T5ForConditionalGeneration.from_pretrained('castorini/monot5-base-msmarco').to(device).eval()
        self.model = model

        if not tokenizer:
            tokenizer = T5BatchTokenizer(AutoTokenizer.from_pretrained('t5-base'), batch_size=8)
        self.tokenizer = tokenizer

        self.device = next(self.model.parameters(), None).device


class SequenceClassificationTransformerReranker(Reranker):
    def __init__(self,
                 model: PreTrainedModel,
                 tokenizer: PreTrainedTokenizer):
        if not model:
            device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
            model = AutoModelForSequenceClassification.from_pretrained('castorini/monobert-large-msmarco').to(device).eval()
        self.model = model

        if not tokenizer:
            tokenizer = AutoTokenizer.from_pretrained('bert-large-uncased')
        self.tokenizer = tokenizer

        self.device = next(model.parameters()).device
```

or 

making subclasses:
```python
class MonoT5(T5Reranker):
    def __init__(self,
                 model: T5ForConditionalGeneration = None,
                 tokenizer: QueryDocumentBatchTokenizer = None):
        if not model:
            device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
            model = T5ForConditionalGeneration.from_pretrained('castorini/monot5-base-msmarco').to(device).eval()
        if not tokenizer:
            tokenizer = T5BatchTokenizer(AutoTokenizer.from_pretrained('t5-base'), batch_size=8)
        super().__init__(model, tokenizer)

class MonoBERT(SequenceClassificationTransformerReranker):
    def __init__(self,
                 model: T5ForConditionalGeneration = None,
                 tokenizer: QueryDocumentBatchTokenizer = None):
        if not model:
            device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
            model = AutoModelForSequenceClassification.from_pretrained('castorini/monobert-large-msmarco').to(device).eval()
        if not tokenizer:
            tokenizer = AutoTokenizer.from_pretrained('bert-large-uncased')
        super().__init__(model, tokenizer)
```

**Comment by lintool** [comment]
My vote is for option 1, but renaming the classes `monoT5` and `monoBERT`. I know this is against Python conventions, but is started with lowercase "m" really that bad? Makes it consistent with our papers, etc.

@ronakice should chime in also...

Also, once we build these abstractions we should propagate to the replications also, e.g.,:
https://github.com/castorini/pygaggle/blob/master/pygaggle/run/evaluate_passage_ranker.py

**Comment by ronakice** [comment]
I agree with @lintool, lowercase "m" as it is consistent with our previous work!

**Comment by lintool** [comment]
> I agree with @lintool, lowercase "m" as it is consistent with our previous work!

But re: Option 1 vs. Option 2? I.e., is there something special about our current abstractions that we should keep?

**Comment by yuxuan-ji** [comment]
the main things I can think of with using lowercase are
1. pretty much every linter will complain unless it's added as an exception
2.  it's not exactly clear from seeing `from pygaggle.rerank.transformers import monoBERT, monoT5` that those are classes

I'd avoid it unless the consistency w/ paper is particularly important and worth ignoring Python's conventions

**Comment by ronakice** [comment]
Hey @yuxuan-ji  sorry I got a bit carried away with some other work.

Firstly, yes I think option 1 is better. You make a fair point about linters complaining about monoBERT/monoT5 as well as the lack of clarity to the general dev. So I concede, I think it is better to go with `MonoBERT` and `MonoT5`. @lintool what do you think?

As to the usage of `MonoBERT` in the general form, I think it is mostly fine since all these other Sequence Classification transformers are kinda BERT derived and use the same "principles", unlike monoT5 which signified a bit of a shift. Also, we currently only support `MonoBERT` so until we find a better name :)/add support for other models, we shouldn't worry about it.

**Comment by lintool** [comment]
Okay, we've converged. Option 1, `MonoBERT` and `MonoT5` as class names.

FWIW - huggingface made the model names fugly, favoring conformance to conventions - see [Bert](https://huggingface.co/transformers/model_doc/bert.html) and [MBart](https://huggingface.co/transformers/master/model_doc/mbart.html).

@yuxuan-ji please execute.

**Review by ronakice — APPROVED** [review]
LGTM! Merging! Thanks @yuxuan-ji  for swiftly finishing this :)

**Pull request merged**
