### PR TITLE
Adds reranker example

### PR DESCRIPTION
**Pull request by rodrigonogueira4**

### CODE REVIEW

**Comment by rodrigonogueira4** [comment]
Regarding exa

> Can we give a slightly more meaningful example to show that it indeed works? And should we move this to `docs/`

Regarding a meaningful example, sure!
Regarding moving to docs/, I think this code needs to be in the main README.md as they can find it more easily.

**Comment by Fatima-200159617** [comment]
I am trying to use monobert instead of T5. Here is the code

import torch
from transformers import PreTrainedModel,PreTrainedTokenizer,AutoTokenizer,AutoModel
from pygaggle.rerank.base import Query, Text
from pygaggle.rerank.transformer import SequenceClassificationTransformerReranker
model_name = 'castorini/monobert-large-msmarco'
tokenizer_name = 'castorini/monobert-large-msmarco'
batch_size = 8
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
model = AutoModel.from_pretrained("castorini/monobert-large-msmarco")
model = model.to(device).eval()
tokenizer = AutoTokenizer.from_pretrained(tokenizer_name)
reranker =  SequenceClassificationTransformerReranker(model, tokenizer)
query = Query('how old are you?')
doc1 = Text('I am 77 years old')
doc2 = Text('I am hungry')
documents = [doc1,doc2]
scores = [result.score for result in reranker.rerank(query, documents)]
print(scores)
Could you please advice on what is the right tokenizer to use as I am having an issue running it.

**Comment by rodrigonogueira4** [comment]
Hi Fatima,

Could you try `tokenizer_name = 'bert-large-uncased'`?

**Comment by Fatima-200159617** [comment]
I tried I a getting the same error shown below:
ValueError                                Traceback (most recent call last)

<ipython-input-7-5b65cf5be7bc> in <module>()
     15 doc2 = Text('I am hungry')
     16 documents = [doc1,doc2]
---> 17 scores = [result.score for result in reranker.rerank(query, documents)]
     18 print(scores)
     19 print(sorted(scores,reverse=True))

1 frames

/content/gdrive/My Drive/Reranking-pygaggle/pygaggle/pygaggle/rerank/transformer.py in rerank(self, query, texts)
    117             input_ids = ret['input_ids'].to(self.device)
    118             tt_ids = ret['token_type_ids'].to(self.device)
--> 119             output, = self.model(input_ids, token_type_ids=tt_ids)
    120             if output.size(1) > 1:
    121                 text.score = torch.nn.functional.log_softmax(

ValueError: too many values to unpack (expected 1)

**Comment by Fatima-200159617** [comment]
The below code worked for me

**Comment by Fatima-200159617** [comment]
#monoBert reranker
import torch
# from transformers import PreTrainedModel,PreTrainedTokenizer,AutoTokenizer,AutoModel,BertTokenizer,BertForSequenceClassification
from transformers import BertTokenizer,BertForSequenceClassification
from pygaggle.rerank.base import Query, Text
from pygaggle.rerank.transformer import SequenceClassificationTransformerReranker
model_name = 'castorini/monobert-large-msmarco'
tokenizer_name = 'bert-large-uncased'
batch_size = 8
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
model =  BertForSequenceClassification.from_pretrained("castorini/monobert-large-msmarco")
model = model.to(device).eval()
tokenizer = BertTokenizer.from_pretrained(tokenizer_name)
reranker =  SequenceClassificationTransformerReranker(model, tokenizer)
query = Query('how old are you?')
doc1 = Text('I am 77 years old')
doc2 = Text('I am hungry')
doc3=Text('My age is 77')
doc4=Text('I want to sleep early')
documents = [doc1,doc2,doc3,doc4]
scores = [result.score for result in reranker.rerank(query, documents)]
print(scores)
print(sorted(scores,reverse=True))

**Comment by Fatima-200159617** [comment]
The below code worked for me 
#monoBert reranker
import torch
from transformers import BertTokenizer,BertForSequenceClassification
from pygaggle.rerank.base import Query, Text
from pygaggle.rerank.transformer import SequenceClassificationTransformerReranker
model_name = 'castorini/monobert-large-msmarco'
tokenizer_name = 'bert-large-uncased'
batch_size = 8
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
model =  BertForSequenceClassification.from_pretrained("castorini/monobert-large-msmarco")
model = model.to(device).eval()
tokenizer = BertTokenizer.from_pretrained(tokenizer_name)
reranker =  SequenceClassificationTransformerReranker(model, tokenizer)
query = Query('how old are you?')
doc1 = Text('I am 77 years old')
doc2 = Text('I am hungry')
doc3=Text('My age is 77')
doc4=Text('I want to sleep early')
documents = [doc1,doc2,doc3,doc4]
scores = [result.score for result in reranker.rerank(query, documents)]
print(scores)

**Comment by rodrigonogueira4** [comment]
Great, thanks, Fatima!

I've created a pull request that exemplifies how to use the BERT reranker: https://github.com/castorini/pygaggle/pull/59

**Comment by Fatima-200159617** [comment]
> 
> 
> Great, thanks, Fatima!
> 
> I've created a pull request that exemplifies how to use the BERT reranker: #59

Thanks a lot for the code.

**Pull request merged**
