### PR TITLE
Replication for MS MARCO passage on Colab

### PR DESCRIPTION
**Pull request by qguo96**
Replication on Colab is successful.

Colab Environment:
OS: Ubuntu-18.04.3 LTS
Java: 11.0.8
Python: 3.6.9

results are shown below:
Re-Ranking with monoBERT:
Screenshot (1157)

Re-Ranking with monoT5:
Screenshot (1162)

### CODE REVIEW

**Comment by qguo96** [comment]
I add a Colab notebook under `pygaggle/notebooks`. Otherwise, it takes too much space. I'm not sure if this is a good idea.

**Comment by lintool** [comment]
I was just thinking this - add a section of prose to here: https://github.com/castorini/pygaggle/blob/master/docs/experiments-msmarco-passage.md

describing any tips/tricks to getting the replication colab, as opposed to including the entire notebook... we want to URAs that come after to actually do some work... ;) and not just click "run all cells!"

thoughts @ronakice ?

**Comment by qguo96** [comment]
Is the guide concise enough? I followed the guide and redid it again. Newcomers may need a little time to understand.

**Comment by ronakice** [comment]
Yep, I think that's why I was hesitant to share the notebooks (although I have some for MS MARCO Passage and CovidQA since that's how I initially ran the experiments).

**Comment by ronakice** [comment]
@lintool @qguo96 I also think we should move these instructions to convert Colab into a GPU instance with full SSH access, elsewhere. While it is very useful, I think it needs to be in some other place since it is useful for all instructions?

**Comment by lintool** [comment]
Created new repo for holding this information: https://github.com/castorini/onboarding

@qguo96 sorry about changing our mind. Can send PR against this new repo for your instructions?

And I thought the replication log "Results replicated by ... (Tesla T4 on Colab)" should make it clear that this was on Colab?

**Comment by qguo96** [comment]
Get it. I would make a new PR for this new repo.

**Review by lintool — APPROVED** [review]

**Pull request merged**
