### PR TITLE
fix inconsistency re upgrading to transformer 4.0.0 

### PR DESCRIPTION
**Pull request by MXueguang**
1. `sentencepiece` need to be installed saperately in transformers 4.0.0 for slow Tokenizers e.g. T5Tokenizer.
2. set `use_fast=False` for Tokenizers to make sure tokenizers have same behavior as before
3. change "max_length" padding for T5 to "longest" padding which gives same result with taking 1/3 time.

replicated msmarco-subset
https://colab.research.google.com/drive/1xt0a-EvGO7zprCoBUjtBQFdB4WL9nwuT?usp=sharing

### CODE REVIEW

**Comment by ronakice** [comment]
Just a comment, but what happens if we go with fast tokenizers?

**Comment by ronakice** [comment]
Was that the result I was getting?

**Review by ronakice — APPROVED** [review]
LGTM!

**Comment by MXueguang** [comment]
> Was that the result I was getting?

same to the scores in `experiments-msmarco-passage-subset.md`

**Comment by MXueguang** [comment]
> Just a comment, but what happens if we go with fast tokenizers?

MonoBert gives same result as before but monoT5 is not giving same result

**Pull request merged**
