### PR TITLE
Update MS MARCO Passage Replication Log

### PR DESCRIPTION
**Pull request by HangCui0510**
Screen Shot 2020-05-29 at 4 03 49 AM
Screen Shot 2020-05-29 at 4 04 29 AM
Screen Shot 2020-05-29 at 4 57 53 AM
Screen Shot 2020-05-29 at 4 58 23 AM

### CODE REVIEW

**Comment by ronakice** [comment]
Hey! Great work @HangCui0510 ! Do you mind sharing the command for monot5-base. Also since you were running on colab, can you also verify if using --model-name-or-path castorini/monobert-large-msmarco instead works? Thanks :)

**Comment by HangCui0510** [comment]
@ronakice 
Command for monot5-base
Screen Shot 2020-05-29 at 12 47 29 PM

--model-name-or-path castorini/monobert-large-msmarco works

Screen Shot 2020-05-29 at 4 15 34 PM
Screen Shot 2020-05-29 at 4 15 22 PM

**Comment by ronakice** [comment]
Looks good thanks for clarifying, we're just trying to get to see why it doesn't show up in huggingface! @lintool seems like although he runs it doesn't seem to update the "count". Maybe it lags behind by a bit! Merging!

**Comment by lintool** [comment]
I love to count. And leaderboards.

**Comment by ronakice** [comment]
ha, count von count. There's a muppet-kind name still up for grabs ;) (or so I think)

**Pull request merged**
