### PR TITLE
MS MARCO passage replication

### PR DESCRIPTION
**Pull request by saileshnankani**
Platform: Colab
Issues: `pip install pygaggle` gives the following raise:
```
colab cannot import name 'save_state_warning' from 'torch.optim.lr_scheduler'
```

Running `pip install torch==1.7.0` solves this issue.

## Re-Ranking with monoBERT
```
evaluate_passage_ranker: precision@1 0.066667
evaluate_passage_ranker: recall@3    0.21587
evaluate_passage_ranker: recall@50   0.55079
evaluate_passage_ranker: recall@1000 0.84762
evaluate_passage_ranker: mrr         0.17093
evaluate_passage_ranker: mrr@10      0.15907
```

## Re-Ranking with monoT5
```
evaluate_passage_ranker: precision@1 0.066667
evaluate_passage_ranker: recall@3    0.21587
evaluate_passage_ranker: recall@50   0.55079
evaluate_passage_ranker: recall@1000 0.84762
evaluate_passage_ranker: mrr         0.17093
evaluate_passage_ranker: mrr@10      0.15907
```

---------
Details and reproduction results can be found [in the notebook](https://colab.research.google.com/drive/1XLqsP02p9ckT9ATWTsrWYpaG6ze7Dizi?usp=sharing)

### CODE REVIEW

**Comment by ronakice** [comment]
Hey @saileshnankani , a first task would be figuring out how to fix these scores as they don't match our documentation. Someone successfully replicated in https://github.com/castorini/pygaggle/commit/7c0ebbeb20dc867ee68d21c6ac7da84073bdb6f6. Can you try this commit out, evaluate to see if you match our documented scores, and then try to isolate what's causing the issue?

Thanks!

**Comment by saileshnankani** [comment]
I think the commit, [13b308e](https://github.com/castorini/pygaggle/commit/13b308ee4c316b85205c39ff2bca5b8a956dbf7c), is causing the issue. I reverted this commit and ran the replication again to get the correct values

**Comment by ronakice** [comment]
I see what's going wrong, we need to create some method in `rescore` for all the `Reranker` such that the sorting isn't done in the end, and have this `rerank` method just call the sorting function. Finally, in all our evaluation scripts that use the `rerank` method, make sure to use `rescore` instead, sg? Will be great if you can work on this, simple enough.

**Comment by rodrigonogueira4** [comment]
Why sorting _twice_ by score causing this issue?

**Comment by ronakice** [comment]
In the other place we are using the https://github.com/castorini/pygaggle/blob/07b47ea9f1f3a827c6e09b3fce8687c69ebc6d18/pygaggle/model/evaluate.py#L165
and the `examples` are passed on (not sorted) to the writer and scores along with the scores (sorted). This causes the mismatch.

**Comment by rodrigonogueira4** [comment]
If the `example` object already contains the scores for each document, we should pass to the writer only that object, and not a pair (`scores`, `example`). E.g.:
```
if self.writer is not None:
    self.writer.write(example)
```

https://github.com/castorini/pygaggle/blob/07b47ea9f1f3a827c6e09b3fce8687c69ebc6d18/pygaggle/model/evaluate.py#L167

Otherwise, it becomes ambiguous which score the writer will use.

**Comment by ronakice** [comment]
A simpler workaround could be just removing all the deepcopy's in the rerank class, then we can just pass `example` for writing and scoring like you said. Wouldn't need a `rescore` method? What do you think?

**Comment by rodrigonogueira4** [comment]
That will break other people's code (include some of mine) that assume rerank does not change `texts`.
I still think removing `scores` from `write()` is a cleaner solution since `example` already contains document scores.

**Comment by ronakice** [comment]
thing is how can you just pass `example` in `write()` though? The new scores are not part of `example` if you see what `rerank()` does?

**Comment by rodrigonogueira4** [comment]
You just need to replace:
```
scores = [x.score for x in self.reranker.rerank(example.query, example.documents)]
```
with:
```
example.documents = self.reranker.rerank(example.query, example.documents)
```

**Comment by ronakice** [comment]
Ohh yes, you can do that true, I incorrectly assumed you meant to say you didn't want `example.documents` to be updated anywhere but I guess you mean not in `rerank`. @saileshnankani can you do as suggested here?

**Comment by saileshnankani** [comment]
I tried doing as discussed above i.e.[ removing scores from write](https://github.com/castorini/pygaggle/compare/master...saileshnankani:fix-rerank-evaluator) (by making it an optional parameter). However, when I [ran the experiment again](https://colab.research.google.com/drive/1F0Uo9y9m1mtaKtczom2wwTLjVD6uCxjH?authuser=1#scrollTo=acgSAAuisj0P) using the new code, it still gives me the incorrect results.

**Comment by rodrigonogueira4** [comment]
Since the metrics are exactly the same from BM25, it seems `example.documents` is not being updated with the new scores from T5. Could you please verify that?

**Comment by andrewyguo** [comment]
@saileshnankani 
I ran into the same issue and am seeing the same scores as you have. Please let me know if you manage to fix this issue.

**Comment by saileshnankani** [comment]
I'm getting the same low metrics as above when either of the following is true:
- Documents and score mismatch (which what we have in master right now)
- examples.documents is updated inside the `evaluate` function. 

I'm still not sure why I am still getting low metrics when examples.documents is updated correctly.

**Comment by saileshnankani** [comment]
> I see what's going wrong, we need to create some method in `rescore` for all the `Reranker` such that the sorting isn't done in the end, and have this `rerank` method just call the sorting function. Finally, in all our evaluation scripts that use the `rerank` method, make sure to use `rescore` instead, sg? Will be great if you can work on this, simple enough.

I will try this solution now instead

**Comment by saileshnankani** [comment]
I implemented the above [here](https://github.com/castorini/pygaggle/compare/master...saileshnankani:add-rescore?expand=1). This gives the correct metrics since it is only really renaming rerank to rescore.

**Comment by rodrigonogueira4** [comment]
SG, but I think rerank should call rescore:
```
def rerank(self, texts: List[Text]) -> List[Text]:
        """Sorts a list of texts
        """
        return self.rescore(texts).sort(lambda x: x.score)
```

**Comment by rodrigonogueira4** [comment]
Also, you need to call `sorted` instead of `sort`

**Comment by saileshnankani** [comment]
Reran the experiment after rebasing with master and updated the replication log. Got better results this time around.

## Re-Ranking with monoBERT
```
evaluate_passage_ranker: precision@1 0.27619
evaluate_passage_ranker: recall@3    0.42698
evaluate_passage_ranker: recall@50   0.81746
evaluate_passage_ranker: recall@1000 0.84762
evaluate_passage_ranker: mrr         0.4109
evaluate_passage_ranker: mrr@10      0.40268
```

## Re-Ranking with monoT5
```
evaluate_passage_ranker: precision@1 0.26667
evaluate_passage_ranker: recall@3    0.46032
evaluate_passage_ranker: recall@50   0.80635
evaluate_passage_ranker: recall@1000 0.84762
evaluate_passage_ranker: mrr         0.39734
evaluate_passage_ranker: mrr@10      0.39044
```

**Pull request merged**
