### PR TITLE
Reproduced MSMARCO passage retrieval (subset) experiment

### PR DESCRIPTION
**Pull request by manveertamber**
Successfully reproduced results
Ubuntu 20.04.03 LTS
Python 3.6.13

### CODE REVIEW

**Comment by lintool** [comment]
Describe your hw setting please? E.g., what GPU?

**Comment by manveertamber** [comment]
GPU: GeForce GTX 1660 6GB 
CPU: AMD Ryzen 5 5600X

**Comment by lintool** [comment]
thanks - I'll let @ronakice take over.

**Comment by ronakice** [comment]
LGTM!

**Pull request merged**
